name:                graphql-hs
version:             0.1.0.0
github:              "githubuser/graphql-hs"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/graphql-hs#readme>

default-extensions:
- DataKinds
- DeriveFunctor
- DeriveGeneric
- DuplicateRecordFields
- ExistentialQuantification
- FlexibleContexts
- FlexibleInstances
- GADTs
- GeneralizedNewtypeDeriving
- KindSignatures
- LambdaCase
- NamedFieldPuns
- NoImplicitPrelude
- MultiParamTypeClasses
- MultiWayIf
- OverloadedLabels
- OverloadedStrings
- PatternSynonyms
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- TupleSections
- TypeApplications
- TypeInType
- TypeOperators

dependencies:
- base >= 4.7 && < 5
- protolude

library:
  source-dirs: src
  dependencies:
  - aeson
  - attoparsec
  - containers
  - ghc-prim
  - row-types
  - scientific
  - QuickCheck
  - text

executables:
  graphql-hs-example:
    main:                Main.hs
    source-dirs:         example
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - graphql-hs
    - http-types
    - ghc-prim
    - row-types
    - wai
    - warp

tests:
  graphql-hs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - graphql-hs
